//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photostok.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAsket
    {
        public int ID { get; set; }
        public string User1 { get; set; }
        public string image1 { get; set; }
        public string namefotograf1 { get; set; }
        public Nullable<int> IDIMage { get; set; }
        public Nullable<int> Idhistory { get; set; }
        public string Prise { get; set; }
    
        public virtual History History { get; set; }
        public virtual Image Image { get; set; }
    }
}
