//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photostok.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAsket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAsket()
        {
            this.User = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string User1 { get; set; }
        public string image1 { get; set; }
        public string namefotograf1 { get; set; }
        public Nullable<int> IDIMage { get; set; }
        public Nullable<int> Idhistory { get; set; }
        public string Prise { get; set; }
        public byte[] imageq { get; set; }
    
        public virtual History History { get; set; }
        public virtual photo photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
