//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photostok.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class karzina
    {
        public int ID { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> IDimage { get; set; }
        public Nullable<int> IDhistory { get; set; }
        public Nullable<int> IDnamefotograf { get; set; }
        public Nullable<int> IDteretory { get; set; }
        public string User1 { get; set; }
        public string image1 { get; set; }
        public string history1 { get; set; }
        public string namefotograf1 { get; set; }
        public string teretory1 { get; set; }
        public string histori1 { get; set; }
    
        public virtual image image { get; set; }
    }
}
