//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photostok.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class photoq
    {
        public int id { get; set; }
        public string name { get; set; }
        public string nameFhotograf { get; set; }
        public string teretory { get; set; }
        public string iso { get; set; }
        public string diofragma { get; set; }
        public string vadergka { get; set; }
        public string price { get; set; }
        public byte[] image { get; set; }
    }
}
