//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photostok.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string NAme { get; set; }
        public string Login { get; set; }
        public string password { get; set; }
        public Nullable<int> karzinaID { get; set; }
        public Nullable<int> historyid { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
